### ISSUE TITLE
Tabulator scrolls back to the top with many rows and sizing_mode="stretch_width"

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2405]
title

**Comment by MarcSkovMadsen** [comment]
Hi @andhuang-CLGX 

Could you provide some more information please? Like versions of packages, description of bug, minimum reproducible example, gif/ video etc.

**Comment by dbotwinick** [comment]
I think I'm having the same issue as the OP. I'm about 2 days into my experiences w/ Panel, so I'll try to help but I'm still getting my bearings. 

I'm currently trying to make a logging widget (also discovered https://github.com/holoviz/panel/issues/1978) but I wanted to be able to filter my logs by level, source modules, etc., so I wanted to use a table with columns. While using the Tabulator widget in a panel.serve() environment (not within a Jupyter notebook), I've found that every stream call event sent to the Tabulator causes the table to scroll back to the top. If follow=True is enabled in the .stream() function, then after the table scrolls to the top, it scrolls to the bottom to "follow". (paging is disabled). Therefore, it becomes impossible to interact with (or use) the table because it's stuck constantly scrolling up and down. (video shown w/ 250ms period between updates). 

https://user-images.githubusercontent.com/6953152/126426441-290da2cd-30f5-46f5-b606-d504db2c221b.mp4

I actually found the same scrolling behavior to happen in the Perspective pane as well, but I don't know if that's indicative of anything. It seems like as currently implemented (I'll start working my way into the internals...) the calls to stream aren't necessarily taking advantage of the functionality inherent to tabulator for adding rows--it's all handled in Panels and a revised full dataset is sent to Tabulator? At least that's how it seems at a glance until I get my bearings through the layers of abstraction inherent in panel & bokeh. 

I wrote a quick sanitized sample that produces this outcome using the latest panel 0.12.0. When I run this, I get a bunch of errors--but it still produces the same outcome as other code I've spent more time on.

```
from itertools import count
from time import time

import pandas as pd
import panel as pn
from bokeh.models import DateFormatter, NumberFormatter

template = pn.template.BootstrapTemplate(title='Tabulator Scrolling')
start_time = time()
counter = count()


def make_msg(i):
    return pd.DataFrame.from_dict({
        'sent': [pd.Timestamp(start_time + i, unit='s')],
        'lvl': ['INFO'],
        'runtime': [i / 10],
        'service': ['service'],
        'component': ['component'],
        'msg': [f'sample msg {i}'],  
    })


table = pn.widgets.Tabulator(
    make_msg(next(counter)),
    titles={
        'sent': 'Sent',
        'lvl': 'Level',
        'runtime': 'Runtime',
        'service': 'Service',
        'component': 'Component',
        'msg': 'Message',
    },
    formatters={
        'sent': DateFormatter(format='%Y-%m-%d %H:%M:%S'),
        'runtime': NumberFormatter(format='+0.0')
    },
    min_height=450,
)


def send_new_msg():
    table.stream(make_msg(next(counter)), rollover=500, follow=True)


template.main.append(pn.Row(table))
pn.state.add_periodic_callback(send_new_msg, period=250)
```

Note that I am running the above code via panel.serve (not inside of a jupyter notebook).

**Comment by philippjfr** [comment]
Suspect when a resize event is triggered that triggers a relayout event on the component which ends up scrolling back to the top. Best way to fix that will probably be to persist the current view and restore it. Total guess but it would explain things. Will schedule for 0.12.1

**Comment by dbotwinick** [comment]
> Suspect when a resize event is triggered that triggers a relayout event on the component which ends up scrolling back to the top. Best way to fix that will probably be to persist the current view and restore it. Total guess but it would explain things. Will schedule for 0.12.1

Thanks for quick response. I'll dig into this more some time in the next few days. From looking at the tabulator docs, it looks like it might be use of setData vs replaceData when manipulating tabulator js? If that's the case, that could be a really quick fix. 

---
![image](https://user-images.githubusercontent.com/6953152/126528484-88c27b1f-fca4-476c-96c9-999a126d5137.png)
see: http://tabulator.info/docs/4.9/update
---
Of course, since tabulator also includes an 'addData' function--it would potentially also be nice to use that, but the problem there is I guess it would make it either more complicated or less efficient to maintain synchronized state. I might end up wrapping tabulator myself and just using addData--depending on what I find as I dig into the actual implementation... but I could see why using 'addData' may not actually be advantageous for general usage of tabulator... but that being said, it would be nice if using it were exposed to the user as an option since I think there would be _some_ use cases that would call for it. On that note, I would love to use 'addData' because I could set the default addRowPos to the top and actually have the newest logs come in at the top--then one of my problems with scroll position would go away anyway. (That sort of runs into other considerations regarding sorting, filtering, etc., but one thing at a time...)

![image](https://user-images.githubusercontent.com/6953152/126528910-e9012379-5422-468e-9547-9fc254cb2773.png)

**Comment by dbotwinick** [comment]
> From looking at the tabulator docs, it looks like it might be use of setData vs replaceData when manipulating tabulator js? If that's the case, that could be a really quick fix.

FYI. I did a quick trial of replacing setData w/ replaceData in the tabulator.ts file to see what impact that had on the scrolling issue--and that alone didn't seem to resolve it. Honestly it seems like a bit much, but my current focus is to drill down and make sure I understand whole communications chain then modify the implementation to use addData (because I also think that would be more efficient for 'streaming'. The current implementation sets the data for the whole ColumnDataSource every time, so that's not ideal. I'll have to feel out how that works against paging scenarios, but the ColumnsStreamedEvent fired from bokeh seems to have what we need (the data dict embedded in that event is only the new data), but I haven't finished following that through to bokehjs to figure out what happens to it exactly. It seems like a roundabout approach to fixing the scrolling issue but I figure it would both increase the efficiency of tabulator streaming in panels while potentially resolving the scrolling issue--so I'll give it a shot...

**Comment by philippjfr** [comment]
The description here is really not sufficient to figure out what the original issue was but the issue mentioned by @dbotwinick should be fixed by #2900

**Comment by philippjfr** [comment]
So the issue there was that stream updates were triggering other updates which in turn caused a full rerender of the table. That was of course less than ideal, the solution was to filter out internally generated events before they were scheduled on the event loop.

**Comment by ninousf** [comment]
hi
i'm using the version 0.13.0a26 and i still have the same issue

```
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
import numpy as np
import pandas as pd
import panel as pn

button = pn.widgets.Button(name='Update!')
text = pn.widgets.StaticText()

df = pd.DataFrame.from_records([], columns=['name','status'])
tabulator = pn.widgets.Tabulator(df,
                                 height=450,
                                 show_index=True,
)

def button_cbk(event):
    i  = random.randint(0,20)
    name = f'toto_{i}'
    di2 = dict(name=name, status=f'status_{time.time()}')
    df = tabulator.value
    if name in df.name.values:
        idx = int(df.index[df['name'] == name][0])
        text.value = 'update'
        di_update = {k:[(idx-1,v)] for k,v in di2.items()}
        tabulator.patch(di_update)
    else:
        text.value = 'add'
        tabulator.stream(di2, follow=False)
button.on_click(button_cbk)
pn.Column('## Tabulator test', pn.Row(button,text), tabulator).show()
```
